export interface ElifbaStage {
    id: string;
    title: string;
    shortTitle: string;
    category: 'letters' | 'harekes' | 'rules' | 'med' | 'tanwin' | 'quran';
    badgeColor: string;
    icon?: string;
    description: string;
    itemCount: number;
    imgExt: string;
    audioExt: string;
    folder: string;
    subFolder: string;
    items: string[];
}

export const ELIFBA_STAGES: ElifbaStage[] = [
    {
        "id": "harfler",
        "title": "Harfler (28 Temel Harf)",
        "shortTitle": "Harfler",
        "category": "letters",
        "badgeColor": "from-emerald-500 to-green-600",
        "description": "Kur'an-ı Kerim'in 28 temel harfini tanıma ve mahreç okunuşu",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "harfler",
        "subFolder": "harfler",
        "itemCount": 29,
        "items": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29"
        ]
    },
    {
        "id": "ustun1",
        "title": "Üstün - Harfler",
        "shortTitle": "Üstün (H)",
        "category": "harekes",
        "badgeColor": "from-blue-500 to-cyan-600",
        "description": "Üstün harekesi ile harflerin kalın (a) ve ince (e) okunuşu",
        "imgExt": ".jpg",
        "audioExt": ".m4a",
        "folder": "ustun1",
        "subFolder": "ustun1",
        "itemCount": 28,
        "items": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28"
        ]
    },
    {
        "id": "ustun",
        "title": "Üstün - Kelimeler",
        "shortTitle": "Üstün (K)",
        "category": "harekes",
        "badgeColor": "from-sky-500 to-blue-600",
        "description": "Üstünlü harflerle 3 harfli kelimeleri birleştirip okuma",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "ustun",
        "subFolder": "ustun",
        "itemCount": 30,
        "items": [
            "adele",
            "bease",
            "besara",
            "bir1",
            "ceale",
            "cemea",
            "darabe",
            "ehade",
            "ehaze",
            "emera",
            "feale",
            "fetara",
            "hasera",
            "kadera",
            "kesebe",
            "nezele",
            "rafese",
            "razeka",
            "sadeka",
            "vecede",
            "vekabe",
            "velede",
            "verade",
            "veseka",
            "vezene",
            "vezera",
            "yaratti",
            "zehebe",
            "zekera",
            "zerae"
        ]
    },
    {
        "id": "esre1",
        "title": "Esre - Harfler",
        "shortTitle": "Esre (H)",
        "category": "harekes",
        "badgeColor": "from-purple-500 to-indigo-600",
        "description": "Esre harekesi ile harflerin (ı - i) sesleriyle okunuşu",
        "imgExt": ".jpg",
        "audioExt": ".m4a",
        "folder": "esre1",
        "subFolder": "esre1",
        "itemCount": 28,
        "items": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28"
        ]
    },
    {
        "id": "esre",
        "title": "Esre - Kelimeler",
        "shortTitle": "Esre (K)",
        "category": "harekes",
        "badgeColor": "from-violet-500 to-purple-600",
        "description": "Esreli ve üstünlü harfleri kelime içerisinde okuma",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "esre",
        "subFolder": "esre",
        "itemCount": 30,
        "items": [
            "esre1",
            "esre2",
            "esre3",
            "esre4",
            "esre5",
            "esre6",
            "esre7",
            "esre8",
            "esre9",
            "esre10",
            "esre11",
            "esre12",
            "esre13",
            "esre14",
            "esre15",
            "esre16",
            "esre17",
            "esre18",
            "esre19",
            "esre20",
            "esre21",
            "esre22",
            "esre23",
            "esre24",
            "esre25",
            "esre26",
            "esre27",
            "esre28",
            "esre29",
            "esre30"
        ]
    },
    {
        "id": "otre1",
        "title": "Ötre - Harfler",
        "shortTitle": "Ötre (H)",
        "category": "harekes",
        "badgeColor": "from-pink-500 to-rose-600",
        "description": "Ötre harekesi ile harflerin (u - ü) sesleriyle okunuşu",
        "imgExt": ".jpg",
        "audioExt": ".m4a",
        "folder": "otre1",
        "subFolder": "otre1",
        "itemCount": 28,
        "items": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28"
        ]
    },
    {
        "id": "otre",
        "title": "Ötre - Kelimeler",
        "shortTitle": "Ötre (K)",
        "category": "harekes",
        "badgeColor": "from-rose-500 to-pink-600",
        "description": "Üç harekenin karışık kullanıldığı kelimeleri okuma",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "otre",
        "subFolder": "otre",
        "itemCount": 30,
        "items": [
            "otre1",
            "otre2",
            "otre3",
            "otre4",
            "otre5",
            "otre6",
            "otre7",
            "otre8",
            "otre9",
            "otre10",
            "otre11",
            "otre12",
            "otre13",
            "otre14",
            "otre15",
            "otre16",
            "otre17",
            "otre18",
            "otre19",
            "otre20",
            "otre21",
            "otre22",
            "otre23",
            "otre24",
            "otre25",
            "otre26",
            "otre27",
            "otre28",
            "otre29",
            "otre30"
        ]
    },
    {
        "id": "cezm",
        "title": "Cezm (Sükun)",
        "shortTitle": "Cezm",
        "category": "rules",
        "badgeColor": "from-amber-500 to-orange-600",
        "description": "Harfi tutma ve birleştirerek duraklama alıştırmaları",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "cezm",
        "subFolder": "cezm",
        "itemCount": 15,
        "items": [
            "cez1",
            "cez2",
            "cez3",
            "cez4",
            "cez5",
            "cez6",
            "cez7",
            "cez8",
            "cez9",
            "cez10",
            "cez11",
            "cez12",
            "cez13",
            "cez14",
            "cez15"
        ]
    },
    {
        "id": "sedde",
        "title": "Şedde",
        "shortTitle": "Şedde",
        "category": "rules",
        "badgeColor": "from-red-500 to-rose-600",
        "description": "Harfi iki defa (biri sakin, diğeri harekeli) okuma alıştırmaları",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "sedde",
        "subFolder": "sedde",
        "itemCount": 15,
        "items": [
            "cez16",
            "cez17",
            "cez18",
            "cez19",
            "cez20",
            "cez21",
            "cez22",
            "cez23",
            "cez24",
            "cez25",
            "cez26",
            "cez27",
            "cez28",
            "cez29",
            "cez30"
        ]
    },
    {
        "id": "medelif",
        "title": "Med Harfleri: Elif",
        "shortTitle": "Med Elif",
        "category": "med",
        "badgeColor": "from-teal-500 to-emerald-600",
        "description": "Elif harfi ile bir elif miktarı uzatarak okuma",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "medelif",
        "subFolder": "medelif",
        "itemCount": 30,
        "items": [
            "medelif1",
            "medelif2",
            "medelif3",
            "medelif4",
            "medelif5",
            "medelif6",
            "medelif7",
            "medelif8",
            "medelif9",
            "medelif10",
            "medelif11",
            "medelif12",
            "medelif13",
            "medelif14",
            "medelif15",
            "medelif16",
            "medelif17",
            "medelif18",
            "medelif19",
            "medelif20",
            "medelif21",
            "medelif22",
            "medelif23",
            "medelif24",
            "medelif25",
            "medelif26",
            "medelif27",
            "medelif28",
            "medelif29",
            "medelif30"
        ]
    },
    {
        "id": "medvav",
        "title": "Med Harfleri: Vav",
        "shortTitle": "Med Vav",
        "category": "med",
        "badgeColor": "from-cyan-500 to-teal-600",
        "description": "Vav harfi ile uzatarak (û / üü) okuma",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "medvav",
        "subFolder": "medvav",
        "itemCount": 30,
        "items": [
            "medvav1",
            "medvav2",
            "medvav3",
            "medvav4",
            "medvav5",
            "medvav6",
            "medvav7",
            "medvav8",
            "medvav9",
            "medvav10",
            "medvav11",
            "medvav12",
            "medvav13",
            "medvav14",
            "medvav15",
            "medvav16",
            "medvav17",
            "medvav18",
            "medvav19",
            "medvav20",
            "medvav21",
            "medvav22",
            "medvav23",
            "medvav24",
            "medvav25",
            "medvav26",
            "medvav27",
            "medvav28",
            "medvav29",
            "medvav30"
        ]
    },
    {
        "id": "medye",
        "title": "Med Harfleri: Ye",
        "shortTitle": "Med Ye",
        "category": "med",
        "badgeColor": "from-blue-500 to-indigo-600",
        "description": "Ye harfi ile uzatarak (î / ii) okuma",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "medye",
        "subFolder": "medye",
        "itemCount": 30,
        "items": [
            "medye1",
            "medye2",
            "medye3",
            "medye4",
            "medye5",
            "medye6",
            "medye7",
            "medye8",
            "medye9",
            "medye10",
            "medye11",
            "medye12",
            "medye13",
            "medye14",
            "medye15",
            "medye16",
            "medye17",
            "medye18",
            "medye19",
            "medye20",
            "medye21",
            "medye22",
            "medye23",
            "medye24",
            "medye25",
            "medye26",
            "medye27",
            "medye28",
            "medye29",
            "medye30"
        ]
    },
    {
        "id": "ikiustun",
        "title": "Tenvin: İki Üstün",
        "shortTitle": "İki Üstün",
        "category": "tanwin",
        "badgeColor": "from-amber-600 to-yellow-600",
        "description": "İki üstün ile (en - an) sesleri çıkarma alıştırmaları",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "ikiustun",
        "subFolder": "ikiustun",
        "itemCount": 30,
        "items": [
            "ikiustun1",
            "ikiustun2",
            "ikiustun3",
            "ikiustun4",
            "ikiustun5",
            "ikiustun6",
            "ikiustun7",
            "ikiustun8",
            "ikiustun9",
            "ikiustun10",
            "ikiustun11",
            "ikiustun12",
            "ikiustun13",
            "ikiustun14",
            "ikiustun15",
            "ikiustun16",
            "ikiustun17",
            "ikiustun18",
            "ikiustun19",
            "ikiustun20",
            "ikiustun21",
            "ikiustun22",
            "ikiustun23",
            "ikiustun24",
            "ikiustun25",
            "ikiustun26",
            "ikiustun27",
            "ikiustun28",
            "ikiustun29",
            "ikiustun30"
        ]
    },
    {
        "id": "ikiesre",
        "title": "Tenvin: İki Esre",
        "shortTitle": "İki Esre",
        "category": "tanwin",
        "badgeColor": "from-yellow-600 to-amber-700",
        "description": "İki esre ile (in - ın) sesleri çıkarma alıştırmaları",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "ikiesre",
        "subFolder": "ikiesre",
        "itemCount": 30,
        "items": [
            "ikiesre1",
            "ikiesre2",
            "ikiesre3",
            "ikiesre4",
            "ikiesre5",
            "ikiesre6",
            "ikiesre7",
            "ikiesre8",
            "ikiesre9",
            "ikiesre10",
            "ikiesre11",
            "ikiesre12",
            "ikiesre13",
            "ikiesre14",
            "ikiesre15",
            "ikiesre16",
            "ikiesre17",
            "ikiesre18",
            "ikiesre19",
            "ikiesre20",
            "ikiesre21",
            "ikiesre22",
            "ikiesre23",
            "ikiesre24",
            "ikiesre25",
            "ikiesre26",
            "ikiesre27",
            "ikiesre28",
            "ikiesre29",
            "ikiesre30"
        ]
    },
    {
        "id": "ikiotre",
        "title": "Tenvin: İki Ötre",
        "shortTitle": "İki Ötre",
        "category": "tanwin",
        "badgeColor": "from-orange-600 to-red-600",
        "description": "İki ötre ile (ün - un) sesleri çıkarma alıştırmaları",
        "imgExt": ".png",
        "audioExt": ".mp3",
        "folder": "ikiotre",
        "subFolder": "ikiotre",
        "itemCount": 30,
        "items": [
            "ikiotre1",
            "ikiotre2",
            "ikiotre3",
            "ikiotre4",
            "ikiotre5",
            "ikiotre6",
            "ikiotre7",
            "ikiotre8",
            "ikiotre9",
            "ikiotre10",
            "ikiotre11",
            "ikiotre12",
            "ikiotre13",
            "ikiotre14",
            "ikiotre15",
            "ikiotre16",
            "ikiotre17",
            "ikiotre18",
            "ikiotre19",
            "ikiotre20",
            "ikiotre21",
            "ikiotre22",
            "ikiotre23",
            "ikiotre24",
            "ikiotre25",
            "ikiotre26",
            "ikiotre27",
            "ikiotre28",
            "ikiotre29",
            "ikiotre30"
        ]
    },
    {
        "id": "cuz",
        "title": "Kur'an-ı Kerim / Cüz Okuma",
        "shortTitle": "Cüz / Kur'an",
        "category": "quran",
        "badgeColor": "from-emerald-600 via-teal-600 to-cyan-600",
        "description": "Elifba tamamlandıktan sonra Cüz ve Kur'an-ı Kerim sayfa takibi",
        "imgExt": "",
        "audioExt": "",
        "folder": "",
        "subFolder": "",
        "itemCount": 30,
        "items": []
    }
];

export const CATEGORY_LABELS: Record<ElifbaStage['category'], { label: string; color: string }> = {
    letters: { label: 'Harfler', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30' },
    harekes: { label: 'Harekeler', color: 'bg-sky-500/20 text-sky-300 border-sky-500/30' },
    rules: { label: 'Kurallar (Cezm/Şedde)', color: 'bg-amber-500/20 text-amber-300 border-amber-500/30' },
    med: { label: 'Med Harfleri', color: 'bg-teal-500/20 text-teal-300 border-teal-500/30' },
    tanwin: { label: 'Tenvinler', color: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30' },
    quran: { label: "Kur'an & Cüz", color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30' },
};

/**
 * Belirli bir aşama ve kart index'i için public URL'lerini döndürür.
 * @param stageId Aşama ID'si (örn. 'ustun1')
 * @param itemIndex 1'den başlayan kart sırası (örn. 1, 2, ... 28)
 */
export function getStageItemAssetUrls(stageId: string, itemIndex: number): { img: string; audio: string; name: string } | null {
    const stage = ELIFBA_STAGES.find(s => s.id === stageId);
    if (!stage || stage.category === 'quran' || !stage.items || stage.items.length === 0) return null;

    const idx = Math.max(1, Math.min(itemIndex, stage.items.length)) - 1;
    const itemName = stage.items[idx];

    const base = `/elifba/${stage.folder}/${stage.subFolder}/${itemName}`;
    return {
        name: itemName,
        img: `${base}${stage.imgExt}`,
        audio: `${base}${stage.audioExt}`
    };
}
