
import type { ShopItem } from './types';
import { FlameBadge, SnowflakeBadge, CrownBadge, ShieldBadge, BoltBadge, StarBadge, BrainBadge, HeartBadge, BookBadge, GamepadBadge, MusicBadge, AtomBadge, DjBadge, InfinityBadge, PixelHeartBadge, HilalBadge, KabeBadge, CamiBadge, TesbihBadge, GraduationCapBadge, LightbulbBadge, PencilBadge, TelescopeBadge, CompassBadge, ZodiacBadge, PoliceBadge, DoctorBadge, ChefBadge, SpyBadge, FootballBadge, BasketballBadge, AstronautBadge, GsBadge, FbBadge, BjkBadge, LetterABadge, LetterBBadge, LetterCBadge, LetterCcBadge, LetterDBadge, LetterEBadge, LetterFBadge, LetterGBadge, LetterGgBadge, LetterHBadge, LetterIBadge, LetterIiBadge, LetterJBadge, LetterKBadge, LetterLBadge, LetterMBadge, LetterNBadge, LetterOBadge, LetterOoBadge, LetterPBadge, LetterRBadge, LetterSBadge, LetterSsBadge, LetterTBadge, LetterUBadge, LetterUuBadge, LetterVBadge, LetterYBadge, LetterZBadge } from '@/components/icons';

export const SHOP_ITEMS: ShopItem[] = [
  // Avatar Frames
  {
    id: 'frame_rainbow',
    name: 'Gökkuşağı Sınırı',
    price: 1000,
    type: 'avatarFrame',
    assetUrl: 'conic-gradient(from 180deg at 50% 50%, #ffc800, #ff0080, #00a2ff, #00f0a0, #ffc800)',
    description: 'Profilinize renk katın.',
  },
  {
    id: 'frame_gold',
    name: 'Altın Çerçeve',
    price: 2500,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #f7971e, #ffd200)',
    description: 'Prestijinizi gösterin.',
  },
   {
    id: 'frame_fire',
    name: 'Alev Çerçevesi',
    price: 1200,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #ff416c, #ff4b2b)',
    description: 'Ateşli bir ruh için.',
  },
  {
    id: 'frame_ocean',
    name: 'Okyanus Esintisi',
    price: 750,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #136a8a, #267871)',
    description: 'Sakin ve ferahlatıcı bir dokunuş.',
  },
  {
    id: 'frame_forest',
    name: 'Orman Yeşili',
    price: 750,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #134e5e, #71b280)',
    description: 'Doğayla iç içe bir görünüm.',
  },
  {
    id: 'frame_galaxy_purple',
    name: 'Mor Galaksi',
    price: 1500,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #480048, #C04848)',
    description: 'Evrenin gizemini taşıyın.',
  },
  {
    id: 'frame_sunrise',
    name: 'Gündoğumu',
    price: 900,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #F37335, #FDC830)',
    description: 'Her güne yeni bir başlangıç.',
  },
  {
    id: 'frame_candy',
    name: 'Şeker Dükkanı',
    price: 800,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #a8ff78, #78ffd6)',
    description: 'Tatlı ve eğlenceli bir görünüm.',
  },
   {
    id: 'frame_techno',
    name: 'Tekno Devre',
    price: 1800,
    type: 'avatarFrame',
    assetUrl: 'repeating-linear-gradient(45deg, #00ffff, #00ffff 2px, transparent 2px, transparent 10px), repeating-linear-gradient(-45deg, #00ffff, #00ffff 2px, transparent 2px, transparent 10px)',
    description: 'Dijital bir dokunuş.',
  },
  {
    id: 'frame_comic',
    name: 'Çizgi Roman',
    price: 1300,
    type: 'avatarFrame',
    assetUrl: 'radial-gradient(circle, #facc15 10%, transparent 10%), radial-gradient(circle, #facc15 10%, transparent 10%) 5px 5px, linear-gradient(#ef4444 2px, transparent 2px) 0 -1px, linear-gradient(90deg, #ef4444 2px, transparent 2px) -1px 0',
    description: 'Süper kahramanlar gibi.',
  },
  {
    id: 'frame_leaves',
    name: 'Sarmaşık Yapraklar',
    price: 1100,
    type: 'avatarFrame',
    assetUrl: 'repeating-conic-gradient(#22c55e 0% 15%, #16a34a 15% 30%)',
    description: 'Doğal ve taze bir his.',
  },
   {
    id: 'frame_gs',
    name: 'Cimbom Ruhu Çerçevesi',
    price: 1905,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #FDB913 50%, #C10E21 50%)',
    description: 'Sarı kırmızı renklerle desteğini göster.',
  },
  {
    id: 'frame_fb',
    name: 'Kanarya Alevi Çerçevesi',
    price: 1907,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #003366 50%, #FBB03B 50%)',
    description: 'Sarı lacivert renklerle takımını temsil et.',
  },
  {
    id: 'frame_bjk',
    name: 'Kara Kartal Pençesi Çerçevesi',
    price: 1903,
    type: 'avatarFrame',
    assetUrl: 'linear-gradient(to right, #000000 50%, #FFFFFF 50%)',
    description: 'Siyah beyaz asaletiyle fark yarat.',
  },
  // Avatar Badges
  { id: 'badge_letter_a', name: 'Harf Rozeti - A', price: 300, type: 'avatarBadge', description: 'Profilini A harfiyle süsle.', component: LetterABadge },
  { id: 'badge_letter_b', name: 'Harf Rozeti - B', price: 300, type: 'avatarBadge', description: 'Profilini B harfiyle süsle.', component: LetterBBadge },
  { id: 'badge_letter_c', name: 'Harf Rozeti - C', price: 300, type: 'avatarBadge', description: 'Profilini C harfiyle süsle.', component: LetterCBadge },
  { id: 'badge_letter_cc', name: 'Harf Rozeti - Ç', price: 300, type: 'avatarBadge', description: 'Profilini Ç harfiyle süsle.', component: LetterCcBadge },
  { id: 'badge_letter_d', name: 'Harf Rozeti - D', price: 300, type: 'avatarBadge', description: 'Profilini D harfiyle süsle.', component: LetterDBadge },
  { id: 'badge_letter_e', name: 'Harf Rozeti - E', price: 300, type: 'avatarBadge', description: 'Profilini E harfiyle süsle.', component: LetterEBadge },
  { id: 'badge_letter_f', name: 'Harf Rozeti - F', price: 300, type: 'avatarBadge', description: 'Profilini F harfiyle süsle.', component: LetterFBadge },
  { id: 'badge_letter_g', name: 'Harf Rozeti - G', price: 300, type: 'avatarBadge', description: 'Profilini G harfiyle süsle.', component: LetterGBadge },
  { id: 'badge_letter_gg', name: 'Harf Rozeti - Ğ', price: 300, type: 'avatarBadge', description: 'Profilini Ğ harfiyle süsle.', component: LetterGgBadge },
  { id: 'badge_letter_h', name: 'Harf Rozeti - H', price: 300, type: 'avatarBadge', description: 'Profilini H harfiyle süsle.', component: LetterHBadge },
  { id: 'badge_letter_i', name: 'Harf Rozeti - I', price: 300, type: 'avatarBadge', description: 'Profilini I harfiyle süsle.', component: LetterIBadge },
  { id: 'badge_letter_ii', name: 'Harf Rozeti - İ', price: 300, type: 'avatarBadge', description: 'Profilini İ harfiyle süsle.', component: LetterIiBadge },
  { id: 'badge_letter_j', name: 'Harf Rozeti - J', price: 300, type: 'avatarBadge', description: 'Profilini J harfiyle süsle.', component: LetterJBadge },
  { id: 'badge_letter_k', name: 'Harf Rozeti - K', price: 300, type: 'avatarBadge', description: 'Profilini K harfiyle süsle.', component: LetterKBadge },
  { id: 'badge_letter_l', name: 'Harf Rozeti - L', price: 300, type: 'avatarBadge', description: 'Profilini L harfiyle süsle.', component: LetterLBadge },
  { id: 'badge_letter_m', name: 'Harf Rozeti - M', price: 300, type: 'avatarBadge', description: 'Profilini M harfiyle süsle.', component: LetterMBadge },
  { id: 'badge_letter_n', name: 'Harf Rozeti - N', price: 300, type: 'avatarBadge', description: 'Profilini N harfiyle süsle.', component: LetterNBadge },
  { id: 'badge_letter_o', name: 'Harf Rozeti - O', price: 300, type: 'avatarBadge', description: 'Profilini O harfiyle süsle.', component: LetterOBadge },
  { id: 'badge_letter_oo', name: 'Harf Rozeti - Ö', price: 300, type: 'avatarBadge', description: 'Profilini Ö harfiyle süsle.', component: LetterOoBadge },
  { id: 'badge_letter_p', name: 'Harf Rozeti - P', price: 300, type: 'avatarBadge', description: 'Profilini P harfiyle süsle.', component: LetterPBadge },
  { id: 'badge_letter_r', name: 'Harf Rozeti - R', price: 300, type: 'avatarBadge', description: 'Profilini R harfiyle süsle.', component: LetterRBadge },
  { id: 'badge_letter_s', name: 'Harf Rozeti - S', price: 300, type: 'avatarBadge', description: 'Profilini S harfiyle süsle.', component: LetterSBadge },
  { id: 'badge_letter_ss', name: 'Harf Rozeti - Ş', price: 300, type: 'avatarBadge', description: 'Profilini Ş harfiyle süsle.', component: LetterSsBadge },
  { id: 'badge_letter_t', name: 'Harf Rozeti - T', price: 300, type: 'avatarBadge', description: 'Profilini T harfiyle süsle.', component: LetterTBadge },
  { id: 'badge_letter_u', name: 'Harf Rozeti - U', price: 300, type: 'avatarBadge', description: 'Profilini U harfiyle süsle.', component: LetterUBadge },
  { id: 'badge_letter_uu', name: 'Harf Rozeti - Ü', price: 300, type: 'avatarBadge', description: 'Profilini Ü harfiyle süsle.', component: LetterUuBadge },
  { id: 'badge_letter_v', name: 'Harf Rozeti - V', price: 300, type: 'avatarBadge', description: 'Profilini V harfiyle süsle.', component: LetterVBadge },
  { id: 'badge_letter_y', name: 'Harf Rozeti - Y', price: 300, type: 'avatarBadge', description: 'Profilini Y harfiyle süsle.', component: LetterYBadge },
  { id: 'badge_letter_z', name: 'Harf Rozeti - Z', price: 300, type: 'avatarBadge', description: 'Profilini Z harfiyle süsle.', component: LetterZBadge },
  {
    id: 'badge_astronaut',
    name: 'Astronot Rozeti',
    price: 1800,
    type: 'avatarBadge',
    description: 'Uzay maceraperestleri için.',
    component: AstronautBadge,
  },
  {
    id: 'badge_football',
    name: 'Futbol Topu',
    price: 700,
    type: 'avatarBadge',
    description: 'Futbol sahalarının yıldızı.',
    component: FootballBadge,
  },
  {
    id: 'badge_basketball',
    name: 'Basketbol Topu',
    price: 700,
    type: 'avatarBadge',
    description: 'Potaların efendisi.',
    component: BasketballBadge,
  },
  {
    id: 'badge_graduation_cap',
    name: 'Mezuniyet Kepi',
    price: 1800,
    type: 'avatarBadge',
    description: 'Akademik başarıyı temsil eder.',
    component: GraduationCapBadge,
  },
  {
    id: 'badge_lightbulb',
    name: 'Ampul Rozeti',
    price: 950,
    type: 'avatarBadge',
    description: 'Parlak fikirler için!',
    component: LightbulbBadge,
  },
  {
    id: 'badge_pencil',
    name: 'Kalem Rozeti',
    price: 400,
    type: 'avatarBadge',
    description: 'Yazmayı ve çizmeyi sevenler.',
    component: PencilBadge,
  },
  {
    id: 'badge_telescope',
    name: 'Teleskop Rozeti',
    price: 1700,
    type: 'avatarBadge',
    description: 'Evreni ve bilimi keşfet.',
    component: TelescopeBadge,
  },
  {
    id: 'badge_police',
    name: 'Polis Rozeti',
    price: 1200,
    type: 'avatarBadge',
    description: 'Adaletin ve güvenliğin temsilcisi.',
    component: PoliceBadge,
  },
  {
    id: 'badge_doctor',
    name: 'Doktor Rozeti',
    price: 1200,
    type: 'avatarBadge',
    description: 'Sağlık ve şifa dağıtan.',
    component: DoctorBadge,
  },
  {
    id: 'badge_chef',
    name: 'Aşçı Rozeti',
    price: 900,
    type: 'avatarBadge',
    description: 'Mutfak sanatlarının ustası.',
    component: ChefBadge,
  },
  {
    id: 'badge_spy',
    name: 'Casus Rozeti',
    price: 1600,
    type: 'avatarBadge',
    description: 'Gizemli ve dikkatli.',
    component: SpyBadge,
  },
  {
    id: 'badge_zodiac',
    name: 'Yıldız Falı Rozeti',
    price: 1750,
    type: 'avatarBadge',
    description: 'Parlaklığını ve gizemini yansıt.',
    component: ZodiacBadge,
  },
  {
    id: 'badge_compass',
    name: 'Pusula Rozeti',
    price: 1300,
    type: 'avatarBadge',
    description: 'Her zaman doğru yolu bulanlar için.',
    component: CompassBadge,
  },
  {
    id: 'badge_hilal',
    name: 'Hilal Rozeti',
    price: 1500,
    type: 'avatarBadge',
    description: 'İnancın ve kültürün sembolü.',
    component: HilalBadge,
  },
  {
    id: 'badge_kabe',
    name: 'Siyah Küp Rozeti',
    price: 2000,
    type: 'avatarBadge',
    description: 'Kutsal olanın temsili.',
    component: KabeBadge,
  },
  {
    id: 'badge_cami',
    name: 'Kubbe Rozeti',
    price: 1200,
    type: 'avatarBadge',
    description: 'Topluluğun ve ibadetin merkezi.',
    component: CamiBadge,
  },
  {
    id: 'badge_tesbih',
    name: 'Daireler Rozeti',
    price: 800,
    type: 'avatarBadge',
    description: 'Sabır ve zikrin simgesi.',
    component: TesbihBadge,
  },
  {
    id: 'badge_fire',
    name: 'Alev Rozeti',
    price: 500,
    type: 'avatarBadge',
    description: 'Sıcakkanlı ve enerjik.',
    component: FlameBadge,
  },
  {
    id: 'badge_snowflake',
    name: 'Kar Tanesi Rozeti',
    price: 500,
    type: 'avatarBadge',
    description: 'Sakin ve havalı bir duruş.',
    component: SnowflakeBadge,
  },
  {
    id: 'badge_crown',
    name: 'Kraliyet Tacı',
    price: 5000,
    type: 'avatarBadge',
    description: 'Gerçek bir lider olduğunu göster.',
    component: CrownBadge,
  },
  {
    id: 'badge_shield',
    name: 'Kalkan Rozeti',
    price: 750,
    type: 'avatarBadge',
    description: 'Güçlü ve koruyucu.',
    component: ShieldBadge,
  },
  {
    id: 'badge_bolt',
    name: 'Yıldırım Rozeti',
    price: 800,
    type: 'avatarBadge',
    description: 'Hızlı ve dikkat çekici.',
    component: BoltBadge,
  },
  {
    id: 'badge_star',
    name: 'Yıldız Rozeti',
    price: 1250,
    type: 'avatarBadge',
    description: 'Her zaman parlayan bir yıldız.',
    component: StarBadge,
  },
  {
    id: 'badge_brain',
    name: 'Beyin Rozeti',
    price: 1500,
    type: 'avatarBadge',
    description: 'Zeki ve bilgili.',
    component: BrainBadge,
  },
  {
    id: 'badge_heart',
    name: 'Kalp Rozeti',
    price: 600,
    type: 'avatarBadge',
    description: 'Sevgi dolu ve yardımsever.',
    component: HeartBadge,
  },
  {
    id: 'badge_book',
    name: 'Kitap Rozeti',
    price: 1100,
    type: 'avatarBadge',
    description: 'Bilgeliği ve öğrenmeyi seven.',
    component: BookBadge,
  },
  {
    id: 'badge_gamepad',
    name: 'Oyun Kumandası',
    price: 900,
    type: 'avatarBadge',
    description: 'Oyun ve rekabet tutkunu.',
    component: GamepadBadge,
  },
  {
    id: 'badge_music',
    name: 'Müzik Notası',
    price: 700,
    type: 'avatarBadge',
    description: 'Sanat ve müzik ruhlu.',
    component: MusicBadge,
  },
  {
    id: 'badge_atom',
    name: 'Atom Rozeti',
    price: 1600,
    type: 'avatarBadge',
    description: 'Bilim ve keşif tutkunu.',
    component: AtomBadge,
  },
  {
    id: 'badge_dj',
    name: 'DJ Kulaklık',
    price: 850,
    type: 'avatarBadge',
    description: 'Ritmi hisset.',
    component: DjBadge,
  },
  {
    id: 'badge_infinity',
    name: 'Sonsuzluk Rozeti',
    price: 2000,
    type: 'avatarBadge',
    description: 'Sonsuz potansiyel.',
    component: InfinityBadge,
  },
  {
    id: 'badge_pixel_heart',
    name: 'Piksel Kalp',
    price: 650,
    type: 'avatarBadge',
    description: 'Retro oyun sevgisi.',
    component: PixelHeartBadge,
  },
  {
    id: 'badge_gs',
    name: 'Galatasaray Rozeti',
    price: 1905,
    type: 'avatarBadge',
    description: 'Sarı kırmızı sevdanı göster.',
    component: GsBadge,
  },
  {
    id: 'badge_fb',
    name: 'Fenerbahçe Rozeti',
    price: 1907,
    type: 'avatarBadge',
    description: 'Sarı lacivert tutkunu belli et.',
    component: FbBadge,
  },
  {
    id: 'badge_bjk',
    name: 'Beşiktaş Rozeti',
    price: 1903,
    type: 'avatarBadge',
    description: 'Siyah beyaz asaleti.',
    component: BjkBadge,
  },
];
