import { userProgress, course } from '@/lib/data';
import { ProgressCard } from '@/components/dashboard/progress-card';
import { OverviewChart } from '@/components/dashboard/overview-chart';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  BookCheck,
  CheckCircle,
  Clock,
  Target,
} from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import Image from 'next/image';
import { getPlaceholderImage } from '@/lib/placeholder-images';

export default function DashboardPage() {
  const completedCount = userProgress.completedLessons.length;
  const totalLessons = course.lessons.length;
  const completionPercentage = Math.round((completedCount / totalLessons) * 100);
  const totalScores = Object.values(userProgress.scores);
  const averageScore =
    totalScores.length > 0
      ? Math.round(
          totalScores.reduce((acc, score) => acc + score, 0) / totalScores.length
        )
      : 0;
  
  const lastAccessedLesson = course.lessons.find(l => l.id === userProgress.lastAccessedLesson);

  return (
    <div className="grid auto-rows-max items-start gap-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-3">
      <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-4 lg:col-span-2 xl:col-span-3">
        <ProgressCard
          title="Completion"
          value={`${completionPercentage}%`}
          description={`${completedCount} of ${totalLessons} lessons`}
          icon={BookCheck}
        />
        <ProgressCard
          title="Average Score"
          value={`${averageScore}%`}
          description="Across all quizzes"
          icon={Target}
        />
        <ProgressCard
          title="Lessons Completed"
          value={completedCount.toString()}
          description="Well done!"
          icon={CheckCircle}
        />
        <ProgressCard
          title="Time Spent"
          value="4h 30m"
          description="Total learning time"
          icon={Clock}
        />
      </div>
      <div className="grid gap-4 md:gap-8 lg:col-span-2">
        <Card>
          <CardHeader>
            <CardTitle className="font-headline">Progress Overview</CardTitle>
            <CardDescription>
              Your scores on completed lessons.
            </CardDescription>
          </CardHeader>
          <CardContent className="pl-2">
            <OverviewChart />
          </CardContent>
        </Card>
        {lastAccessedLesson && (
          <Card>
            <CardHeader className="flex flex-row items-center gap-4">
                <Image 
                    src={getPlaceholderImage(lastAccessedLesson.slug.includes('calculus') ? 'calculus' : 'differentiation')?.imageUrl || ''}
                    alt={lastAccessedLesson.title}
                    width={100}
                    height={100}
                    className="rounded-lg object-cover"
                    data-ai-hint="abstract technology"
                />
                <div className="grid gap-1">
                    <CardTitle className="font-headline">Continue Learning</CardTitle>
                    <CardDescription>{lastAccessedLesson.title}</CardDescription>
                    <div className="flex items-center gap-2">
                        <Badge variant="secondary">In Progress</Badge>
                        <span className="text-sm text-muted-foreground">{lastAccessedLesson.duration} min</span>
                    </div>
                </div>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground mb-4">
                {lastAccessedLesson.description}
              </p>
              <Button asChild>
                <Link href={`/lessons/${lastAccessedLesson.slug}`}>
                  Go to Lesson
                </Link>
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
       <Card className="xl:col-span-1">
        <CardHeader>
          <CardTitle className='font-headline'>Your Learning Path</CardTitle>
          <CardDescription>
            A personalized path generated by AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">Ready to find out what to learn next? Get a custom learning path based on your goals.</p>
          <Button asChild className="w-full">
            <Link href="/learning-path">Generate My Path</Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
