const VERSES = [
  { text: "Şüphesiz Allah, adaleti, iyilik yapmayı, yakınlara yardım etmeyi emreder; hayasızlığı, fenalık ve azgınlığı da yasaklar.", source: "Nahl Suresi, 90. Ayet" },
  { text: "Sabredin. Şüphesiz Allah sabredenlerle beraberdir.", source: "Enfâl Suresi, 46. Ayet" },
  { text: "Kim zerre miktarı hayır yapmışsa onu görür. Kim de zerre miktarı şer işlemişse onu görür.", source: "Zilzâl Suresi, 7-8. Ayet" },
  { text: "Rabbinizden bağışlanma dileyin. Çünkü O, çok bağışlayandır.", source: "Nûh Suresi, 10. Ayet" },
  { text: "İyilikle kötülük bir olmaz. Sen kötülüğü en güzel bir şekilde önle.", source: "Fussilet Suresi, 34. Ayet" },
  { text: "O göklerin ve yerin nurudur.", source: "Nûr Suresi, 35. Ayet" },
  { text: "Allah'a tevekkül eden kimseye O yeter.", source: "Talak Suresi, 3. Ayet" },
];

const HADITHS = [
  { text: "Sizin en hayırlınız, Kur'an'ı öğrenen ve öğreteninizdir.", source: "Buhârî, Fezâilü'l-Kur'ân, 21" },
  { text: "Kolaylaştırınız, zorlaştırmayınız. Müjdeleyiniz, nefret ettirmeyiniz.", source: "Buhârî, İlim, 11" },
  { text: "Güzel söz sadakadır.", source: "Buhârî, Edeb, 34" },
  { text: "Müslüman, elinden ve dilinden diğer Müslümanların güvende olduğu kimsedir.", source: "Buhârî, İman, 4" },
  { text: "İki nimet vardır ki insanların çoğu onun kıymetini bilmezler: Vücut sağlığı ve boş vakit.", source: "Buhârî, Rikak, 1" },
  { text: "Amellerin en hayırlısı az da olsa devamlı olanıdır.", source: "Buhârî, Rikak, 18" },
  { text: "Dünya, ahiretin tarlasıdır.", source: "Keşfü'l-Hafâ, 1/412" },
];

const DUAS = [
  { name: "Sabah Duası", arabic: "اَللّٰهُمَّ بِكَ اَصْبَحْنَا", text: "Allah'ım! Senin adınla sabahladık, senin adınla akşamladık, senin adınla yaşar, senin adınla ölürüz. Dönüş de sanadır.", source: "Ebû Dâvûd, Edeb, 110" },
  { name: "Akşam Duası", arabic: "اَللّٰهُمَّ بِكَ اَمْسَيْنَا", text: "Allah'ım! Senin adınla akşamladık, senin adınla sabahladık. Senin adınla yaşar ve ölürüz.", source: "Tirmizî, Daavât, 14" },
  { name: "Yemek Duası", arabic: "بِسْمِ اللهِ وَعَلَى بَرَكَةِ اللهِ", text: "Allah'ın adıyla ve Allah'ın bereketi ile yemeye başlıyorum.", source: "Ebû Dâvûd, Etıme, 16" },
  { name: "Yolculuk Duası", arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا", text: "Bunu bize boyun eğdireni tenzih ederiz; yoksa biz buna güç yetiremezdik.", source: "Zuhruf Suresi, 13" },
  { name: "Uyku Duası", arabic: "بِاسْمِكَ اللّٰهُمَّ أَمُوتُ وَأَحْيَا", text: "Allah'ım! Senin adınla ölür (uyur) ve dirilirim (uyanırım).", source: "Buhârî, Daavât, 7" },
  { name: "Sıkıntı Duası", arabic: "لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ", text: "Senden başka ilah yoktur. Seni tenzih ederim. Gerçekten ben zalimlerden oldum.", source: "Enbiyâ Suresi, 87" },
  { name: "Şükür Duası", arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ", text: "Rabbim! Bana, anneme ve babama verdiğin nimetlere şükretmemi ilham et.", source: "Neml Suresi, 19" },
];

const ESMA = [
  { name: "Allah", arabic: "اَللّٰهُ", meaning: "Her türlü hamd, övgü ve yüceltmeye layık olan, varlığı zorunlu olan tek ilah." },
  { name: "Er-Rahmân", arabic: "اَلرَّحْمٰنُ", meaning: "Dünyada tüm varlıklara merhamet eden, sonsuz rahmet sahibi." },
  { name: "Er-Rahîm", arabic: "اَلرَّحِيمُ", meaning: "Ahirette yalnız müminlere merhamet eden, ikramı bol olan." },
  { name: "El-Melik", arabic: "اَلْمَلِكُ", meaning: "Mülkün gerçek sahibi, kâinatın hükümdarı." },
  { name: "El-Kuddûs", arabic: "اَلْقُدُّوسُ", meaning: "Her türlü noksan ve eksiklikten münezzeh olan, mutlak temiz." },
  { name: "Es-Selâm", arabic: "اَلسَّلَامُ", meaning: "Esenlik ve kurtuluş kaynağı, her beladan selamete çıkaran." },
  { name: "El-Mü'min", arabic: "اَلْمُؤْمِنُ", meaning: "İman ve güven veren, inanan kullarını korkulardan emin kılan." },
  { name: "El-Müheymin", arabic: "اَلْمُهَيْمِنُ", meaning: "Her şeyi gözetip koruyan, varlıklar üzerinde hâkimiyeti olan." },
  { name: "El-Azîz", arabic: "اَلْعَزِيزُ", meaning: "İzzet ve şeref sahibi, her şeye galip ve üstün olan." },
  { name: "El-Cebbâr", arabic: "اَلْجَبَّارُ", meaning: "Her şeye gücü yeten, dilediğini zorla yaptırabilen, kırıkları onaran." },
  { name: "El-Mütekebbir", arabic: "اَلْمُتَكَبِّرُ", meaning: "Büyüklük ve ululuk yalnız kendine ait olan, kibriya sahibi." },
  { name: "El-Hâlık", arabic: "اَلْخَالِقُ", meaning: "Her şeyi yoktan yaratan, varlıkları programlayan." },
  { name: "El-Bâri'", arabic: "اَلْبَارِئُ", meaning: "Her şeyi birbirine uygun ve kusursuz yaratan." },
  { name: "El-Musavvir", arabic: "اَلْمُصَوِّرُ", meaning: "Varlıklara şekil ve suret veren, her şeyi tasvir eden." },
  { name: "El-Gaffâr", arabic: "اَلْغَفَّارُ", meaning: "Günahları defalarca bağışlayan, affı bol olan." },
  { name: "El-Kahhâr", arabic: "اَلْقَهَّارُ", meaning: "Her şeye hükmeden, tüm varlıkları kudretiyle ezip geçen." },
  { name: "El-Vehhâb", arabic: "اَلْوَهَّابُ", meaning: "Karşılıksız ve sürekli bağışlayan, ihsanı bol olan." },
  { name: "Er-Rezzâk", arabic: "اَلرَّزَّاقُ", meaning: "Tüm varlıklara rızık veren, rızık vermeyi sürdüren." },
  { name: "El-Fettâh", arabic: "اَلْفَتَّاحُ", meaning: "Her türlü sıkıntıyı açan, hayırların kapısını açan." },
  { name: "El-Alîm", arabic: "اَلْعَلِيمُ", meaning: "Her şeyi en ince ayrıntısına kadar bilen, ilmi sonsuz olan." },
  { name: "El-Kâbid", arabic: "اَلْقَابِضُ", meaning: "Dilediği şeyi daraltan, rızkı ve ruhları tutan." },
  { name: "El-Bâsit", arabic: "اَلْبَاسِطُ", meaning: "Dilediği şeyi genişleten, rızkı ve rahmeti yayan." },
  { name: "El-Hâfid", arabic: "اَلْخَافِضُ", meaning: "İstediğini alçaltan, kâfirleri ve fâsıkları alçaltan." },
  { name: "Er-Râfi'", arabic: "اَلرَّافِعُ", meaning: "İstediğini yükselten, müminlerin derecesini artıran." },
  { name: "El-Mu'izz", arabic: "اَلْمُعِزُّ", meaning: "İstediğine izzet ve şeref veren, aziz kılan." },
  { name: "El-Müzill", arabic: "اَلْمُذِلُّ", meaning: "İstediğini zelil eden, zalimleri hor ve hakir düşüren." },
  { name: "Es-Semî'", arabic: "اَلسَّمِيعُ", meaning: "Her şeyi işiten, seslerin tümünü duyan." },
  { name: "El-Basîr", arabic: "اَلْبَصِيرُ", meaning: "Her şeyi en ince ayrıntısına kadar gören." },
  { name: "El-Hakem", arabic: "اَلْحَكَمُ", meaning: "Hükmeden, hakkı bâtıldan ayıran, adil hâkim." },
  { name: "El-Adl", arabic: "اَلْعَدْلُ", meaning: "Mutlak adil olan, hiçbir zulüm yapmayan." },
  { name: "El-Latîf", arabic: "اَللَّطِيفُ", meaning: "En ince işleri bilen, lütuf ve ihsanı ince olan." },
  { name: "El-Habîr", arabic: "اَلْخَبِيرُ", meaning: "Her şeyden tam anlamıyla haberdar olan, iç yüzünü bilen." },
  { name: "El-Halîm", arabic: "اَلْحَلِيمُ", meaning: "Ceza vermeye gücü yettiği halde affeden, yumuşak davranan." },
  { name: "El-Azîm", arabic: "اَلْعَظِيمُ", meaning: "Sonsuz büyüklük sahibi, azameti her şeyi kuşatan." },
  { name: "El-Gafûr", arabic: "اَلْغَفُورُ", meaning: "Çok bağışlayan, günahları örten." },
  { name: "Eş-Şekûr", arabic: "اَلشَّكُورُ", meaning: "Az amele çok karşılık veren, kullarının şükrünü kabul eden." },
  { name: "El-Aliyy", arabic: "اَلْعَلِيُّ", meaning: "Yüce ve yüksek olan, her şeyin üstünde olan." },
  { name: "El-Kebîr", arabic: "اَلْكَبِيرُ", meaning: "Büyüklükte sınır tanımayan, her şeyden büyük olan." },
  { name: "El-Hafîz", arabic: "اَلْحَفِيظُ", meaning: "Her şeyi koruyan, muhafaza eden ve bilen." },
  { name: "El-Mukît", arabic: "اَلْمُقِيتُ", meaning: "Her canlının rızkını veren, güç ve kuvvet bahşeden." },
  { name: "El-Hasîb", arabic: "اَلْحَسِيبُ", meaning: "Kulların hesabını gören, her şeye yeten." },
  { name: "El-Celîl", arabic: "اَلْجَلِيلُ", meaning: "Sonsuz yücelik, büyüklük ve ululuk sahibi." },
  { name: "El-Kerîm", arabic: "اَلْكَرِيمُ", meaning: "Cömert ve kerem sahibi, ikramı ve ihsanı bol olan." },
  { name: "Er-Rakîb", arabic: "اَلرَّقِيبُ", meaning: "Her şeyi gözeten, her an murakebesini yapan." },
  { name: "El-Mücîb", arabic: "اَلْمُجِيبُ", meaning: "Dualara cevap veren, istekleri karşılayan." },
  { name: "El-Vâsi'", arabic: "اَلْوَاسِعُ", meaning: "Rahmeti ve ilmi her şeyi kuşatan, geniş ve sonsuz olan." },
  { name: "El-Hakîm", arabic: "اَلْحَكِيمُ", meaning: "Her işi hikmetli yapan, sonsuz hikmet sahibi." },
  { name: "El-Vedûd", arabic: "اَلْوَدُودُ", meaning: "Kullarını seven ve sevilmeye en layık olan." },
  { name: "El-Mecîd", arabic: "اَلْمَجِيدُ", meaning: "Şanı yüce, şerefi ve büyüklüğü sonsuz olan." },
  { name: "El-Bâ'is", arabic: "اَلْبَاعِثُ", meaning: "Ölüleri dirilten, kıyamette insanları kabirden kaldıran." },
  { name: "Eş-Şehîd", arabic: "اَلشَّهِيدُ", meaning: "Her şeye şahit olan, hiçbir şey kendisinden gizlenmeyen." },
  { name: "El-Hak", arabic: "اَلْحَقُّ", meaning: "Varlığı zorunlu ve değişmez olan, gerçeğin ta kendisi." },
  { name: "El-Vekîl", arabic: "اَلْوَكِيلُ", meaning: "Kendisine tevekkül edenlerin işlerini en iyi şekilde gören." },
  { name: "El-Kaviyy", arabic: "اَلْقَوِيُّ", meaning: "Sonsuz güç ve kuvvet sahibi, hiçbir şey kendisini aciz bırakamayan." },
  { name: "El-Metîn", arabic: "اَلْمَتِينُ", meaning: "Son derece sağlam ve güçlü olan, gücü eksilmeyen." },
  { name: "El-Veliyy", arabic: "اَلْوَلِيُّ", meaning: "Müminlerin dostu ve yardımcısı, işlerini üstlenen." },
  { name: "El-Hamîd", arabic: "اَلْحَمِيدُ", meaning: "Her türlü övgü ve hamdı hak eden, gerçek anlamda övülmeye layık." },
  { name: "El-Muhsî", arabic: "اَلْمُحْصِي", meaning: "Her şeyin sayısını bilen, hiçbir şeyi dışarıda bırakmayan." },
  { name: "El-Mübdi'", arabic: "اَلْمُبْدِئُ", meaning: "Varlıkları yoktan ve ilk kez yaratan." },
  { name: "El-Muîd", arabic: "اَلْمُعِيدُ", meaning: "Yarattıklarını yok ettikten sonra tekrar yaratan." },
  { name: "El-Muhyî", arabic: "اَلْمُحْيِي", meaning: "Can veren, hayatı yaratan ve bağışlayan." },
  { name: "El-Mümît", arabic: "اَلْمُمِيتُ", meaning: "Ölümü yaratan, her canlıya ölümü tattıran." },
  { name: "El-Hayy", arabic: "اَلْحَيُّ", meaning: "Ezeli ve ebedi hayat sahibi, daima diri olan." },
  { name: "El-Kayyûm", arabic: "اَلْقَيُّومُ", meaning: "Her şeyi var eden ve ayakta tutan, varlığı kendinden olan." },
  { name: "El-Vâcid", arabic: "اَلْوَاجِدُ", meaning: "Her şeyi bulan, hiçbir şeyden yoksun olmayan." },
  { name: "El-Mâcid", arabic: "اَلْمَاجِدُ", meaning: "Şan, şeref ve büyüklük sahibi, ihsanı geniş olan." },
  { name: "El-Vâhid", arabic: "اَلْوَاحِدُ", meaning: "Tek olan, sayısal olarak bir olan, eşsiz ve ortaksız." },
  { name: "Es-Samed", arabic: "اَلصَّمَدُ", meaning: "Her şeyin muhtaç olduğu, hiçbir şeye muhtaç olmayan." },
  { name: "El-Kâdir", arabic: "اَلْقَادِرُ", meaning: "Dilediği her şeyi yapmaya gücü yeten, sonsuz kudret sahibi." },
  { name: "El-Muktedir", arabic: "اَلْمُقْتَدِرُ", meaning: "Her şeye gücü yeten, mutlak güç ve iktidar sahibi." },
  { name: "El-Mukaddim", arabic: "اَلْمُقَدِّمُ", meaning: "Dilediğini öne alan, öncülük veren." },
  { name: "El-Muahhir", arabic: "اَلْمُؤَخِّرُ", meaning: "Dilediğini geri bırakan, öteye alan." },
  { name: "El-Evvel", arabic: "اَلْأَوَّلُ", meaning: "Her şeyden önce var olan, başlangıcı olmayan." },
  { name: "El-Âhir", arabic: "اَلْآخِرُ", meaning: "Her şeyden sonra var olan, sonu olmayan." },
  { name: "Ez-Zâhir", arabic: "اَلظَّاهِرُ", meaning: "Varlığı apaçık olan, delilleriyle her şeyin üstünde olan." },
  { name: "El-Bâtın", arabic: "اَلْبَاطِنُ", meaning: "Gerçek mahiyeti gizli olan, her şeyin iç yüzünü bilen." },
  { name: "El-Vâlî", arabic: "اَلْوَالِي", meaning: "Kâinatı tek başına idare eden, her şeyin mülkünü elinde tutan." },
  { name: "El-Müteâlî", arabic: "اَلْمُتَعَالِي", meaning: "Her şeyin üzerinde yüce olan, yüceliği mutlak olan." },
  { name: "El-Berr", arabic: "اَلْبَرُّ", meaning: "İyiliği, ihsanı ve lütfu bol olan, kullarına karşı çok iyi olan." },
  { name: "Et-Tevvâb", arabic: "اَلتَّوَّابُ", meaning: "Tövbeleri kabul eden, kullarına tövbe kapısını açan." },
  { name: "El-Müntakim", arabic: "اَلْمُنْتَقِمُ", meaning: "Haksızlığa uğrayanların intikamını alan, suçluları cezalandıran." },
  { name: "El-Afüvv", arabic: "اَلْعَفُوُّ", meaning: "Günahları tamamen silen, affı sonsuz olan." },
  { name: "Er-Raûf", arabic: "اَلرَّؤُوفُ", meaning: "Çok şefkatli ve merhametli, kullarına karşı son derece nazik." },
  { name: "Mâlikü'l-Mülk", arabic: "مَالِكُ الْمُلْكِ", meaning: "Mülkün gerçek ve ebedi sahibi, dilediğine mülk veren ve geri alan." },
  { name: "Zü'l-Celâli ve'l-İkrâm", arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", meaning: "Hem büyüklük ve azamet hem de ikram ve ihsan sahibi." },
  { name: "El-Muksit", arabic: "اَلْمُقْسِطُ", meaning: "Her konuda adaleti yerine getiren, hakkı hak sahibine veren." },
  { name: "El-Câmi'", arabic: "اَلْجَامِعُ", meaning: "Kıyamette her şeyi ve herkesi bir araya toplayan." },
  { name: "El-Ganiyy", arabic: "اَلْغَنِيُّ", meaning: "Hiçbir şeye muhtaç olmayan, sonsuz zenginlik sahibi." },
  { name: "El-Muğnî", arabic: "اَلْمُغْنِي", meaning: "Dilediğini zengin eden, ihtiyaçları karşılayan." },
  { name: "El-Mâni'", arabic: "اَلْمَانِعُ", meaning: "Dilediği şeyi engelleyen ve önleyen." },
  { name: "Ed-Dârr", arabic: "اَلضَّارُّ", meaning: "Dilediğine zarar verdiren, elem ve sıkıntı yaratan." },
  { name: "En-Nâfi'", arabic: "اَلنَّافِعُ", meaning: "Dilediğine fayda veren, hayır ve menfaat yaratan." },
  { name: "En-Nûr", arabic: "اَلنُّورُ", meaning: "Alemleri nurlandıran, her şeyi aydınlatan." },
  { name: "El-Hâdî", arabic: "اَلْهَادِي", meaning: "Dilediğini hidayete erdiren, doğru yolu gösteren." },
  { name: "El-Bedî'", arabic: "اَلْبَدِيعُ", meaning: "Eşsiz ve örnek olmaksızın yaratan, icadı hayranlık verici." },
  { name: "El-Bâkî", arabic: "اَلْبَاقِي", meaning: "Varlığının sonu olmayan, ebediyen baki olan." },
  { name: "El-Vâris", arabic: "اَلْوَارِثُ", meaning: "Her şeyin gerçek sahibi, her şey yok olunca varlığı süren." },
  { name: "Er-Reşîd", arabic: "اَلرَّشِيدُ", meaning: "Her şeyi yerli yerine koyan, doğruya ve iyiye yönelten." },
  { name: "Es-Sabûr", arabic: "اَلصَّبُورُ", meaning: "Çok sabırlı olan, isyankârları hemen cezalandırmayıp mühlet veren." },
];
export { VERSES, HADITHS, DUAS, ESMA };
